name: 'Preeti Sharma'
description: 'Providing Notifications'
inputs:
  milliseconds:  # id of input
    description: '10'
    required: true
    default: '1000'
outputs:
  time: # output will be available to future steps
    description: 'The current time after waiting'
runs:
  using: 'node12'
  main: 'dist/index.js'
